# Expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
#       exclude: env,beans
  endpoint:
    health:
      showDetails: when-authorized #show details in actuator/health endpoint

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 30 #Heartbeat interval. Do not change default interval for production. Default 30