# Expose all actuator endpoints
management.endpoints.web.exposure.include: "*"
# management.endpoints.web.exposure.exclude: env,beans

management.endpoint.health.showDetails: when-authorized #show details in actuator/health endpoint

#Heartbeat interval. Do not change default interval for production. Default 30
eureka.instance.leaseRenewalIntervalInSeconds: 5