server:
  port: ${PORT:8901}

#Setting the logging levels for the service
logging:
  file: target/authserver.log
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    es.in2.cloud: DEBUG
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:        
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  #fix for 'java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.' ref: https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
  zipkin:
    baseUrl:  http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  #send 100% (1) of the requests to Zipkin    
          