version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.0.1
    ports:
      - "9092:9092" #TODO can't scale kafka instances with this setup https://github.com/wurstmeister/kafka-docker/issues/211
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  redis:
      image: redis:alpine
      ports:
        - 6379:6379
        
  logspout:
      image: gliderlabs/logspout
      command: syslog://logs2.papertrailapp.com:39865
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        
  database:
      image: postgres:11
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: p0stgr@s
        POSTGRES_DB: eagle_eye_local
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8988:8080

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
      
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
volumes:
  portainer_data:
