server:
  port: ${PORT:8084}

#management:
#  server:
#    port: 9001

logging:
  file: target/licensing.log
  level: #Setting logging levels
    com.netflix: WARN
    org.springframework.web: WARN
    es.in2.cloud: DEBUG
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#ribbon:
#  eager-load:
#    enabled: true # Prevent Zuul timeout on first request. (not helped)

spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers: localhost
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  #fix for 'java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.' ref: https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
  zipkin:
    baseUrl:  http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  #send 100% (1) of the requests to Zipkin
      
security:
  oauth2:
    client:
      client-id: eagleeye
      client-secret: thisissecret
      access-token-uri: http://localhost:8901/oauth/token
      user-authorization-uri: http://localhost:8901/oauth/authorize
    resource:
      user-info-uri: http://localhost:8901/user
      
#hystrix:
#  shareSecurityContext: true  # Fix for: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'request' is not active for the current thread

                