logging.file: target/config-server.log

server.port: ${PORT:8888}
#server.use-forward-headers: true # Whether X-Forwarded-* headers should be applied to the HttpRequest.

logging:
  file: target/authserver.log
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    es.in2.cloud: DEBUG

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DenisKipchakbaev/cloud-finchley-config.git
          #skip-ssl-validation: true # Flag to indicate that SSL certificate validation should 
                                    # be bypassed when communicating with a repository 
                                    # served over an HTTPS connection. Default: *false*
#      discovery:
#        enabled: true

#management.endpoints.web.base-path: /

#eureka:
#  instance:
#    preferIpAddress: true
